import type { NextPage } from 'next';
import Head from 'next/head';
import React, { useEffect, useMemo, useState } from 'react';
import { useForm } from 'react-hook-form';

import { useAddMerchant } from '@modules/hooks/useMerchant';
import type { TMerchant } from '@modules/entities/merchant';

import { useRouter } from 'next/router';
import styles from '@styles/Detail.module.css';

const Home: NextPage = () => {
  const addMerchant = useAddMerchant();

  const { query, push } = useRouter();
  const { register, handleSubmit } = useForm<TMerchant>({
    defaultValues: {
      id: query?.id ? query.id.toString() : '',
      label: query?.label ? query.label.toString() : '',
      category: query?.category ? query.category.toString() : '',
      rating: query?.rating ? query.rating.toString() : '',
    },
  });

  const submitForm = (data: TMerchant) => {
    addMerchant.mutate(
      {
        id: query?.id
          ? parseInt(query.id.toString())
          : Math.random() * 1000,
        label: data.label,
        category: data.category,
        rating: data.rating,
      },
      {
        onSuccess: () => {
          push('/');
        },
        onError: (err) => {
          console.log('TERJADI KESALAHAN: ', err);
        },
      },
    );
  };

  return (
    <div className="bg-gray-100 min-h-screen">
      <Head>
        <title>Krip - Coding Challange</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="p-12 items-center">
          <h1 className="text-center font-bold text-2xl">
            Merchant Detail
          </h1>
          <div className="flex justify-center items-center">
            <div className="mt-12 w-1/2 bg-white p-8 rounded">
              <form onSubmit={handleSubmit(submitForm)}>
                <div className="form-control mb-2">
                  <label htmlFor="label" className="mb-2">
                    <span>Label</span>
                  </label>
                  <input
                    type="text"
                    id="label"
                    placeholder="Merchant label"
                    className="input input-bordered"
                    {...register('label')}
                  />
                </div>
                <div className="form-control mb-2">
                  <label htmlFor="category" className="mb-2">
                    <span>Category</span>
                  </label>
                  <input
                    type="text"
                    id="category"
                    placeholder="Merchant Category"
                    className="input input-bordered"
                    {...register('category')}
                  />
                </div>
                <div className="form-control mb-2">
                  <label htmlFor="rating" className="mb-2">
                    <span>Rating</span>
                  </label>
                  <input
                    type="number"
                    id="rating"
                    placeholder="Merchant Rating"
                    className={`input input-bordered ${styles.inputrating}`}
                    {...register('rating')}
                  />
                </div>
                <button
                  type="submit"
                  className="btn btn-md w-full mt-6"
                >
                  Submit
                </button>
              </form>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
